-- AlterTable
ALTER TABLE "food" ALTER COLUMN "id" DROP DEFAULT,
ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "discount_percent" DROP DEFAULT,
ALTER COLUMN "review_count" DROP DEFAULT,
ALTER COLUMN "is_available" DROP DEFAULT,
ALTER COLUMN "is_featured" DROP DEFAULT,
ALTER COLUMN "is_new" DROP DEFAULT;
DROP SEQUENCE "food_id_seq";
